(defun diff-to-latex ()
  (interactive)
  (pop-to-buffer "Main.hs")
  (inferior-haskell-load-file)
  (pop-to-buffer "*haskell*")
  (message (concat "draw \"" left "\" \""  right "\""))
  (comint-simple-send (inferior-haskell-process) (concat "draw \"" left "\" \""  right "\""))
  (pop-to-buffer "out.ltx")
  (sleep-for 0 500)
  (TeX-command-master)
  (pop-to-buffer "out.pdf")
  (doc-view-revert-buffer t t)
  (sleep-for 0 500)
  (jump-to-register ?h))

(defvar left  "[1[2[7][9]][3][4][5]]")
(defvar right "[8[2[9][10]][3][4][6][7]]")

(defun set-diff-input ()
  (interactive)
  (setq left (read-from-minibuffer "Left: "))
  (setq right (read-from-minibuffer "Right: "))
  (diff-to-latex))

(global-set-key (kbd "C-c C-r") 'diff-to-latex)
(global-set-key (kbd "C-c r") 'set-diff-input)